title: Art of Life

email: coaching.artoflife@gmail.com
facebook: https://www.facebook.com/CoachingByAlex/
instagram: https://www.instagram.com/artoflife_coaching/

baseurl: "/"
url: "https://art-of-life.github.io"
github_username: art-of-life

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from

collections:
    oferta:
        output: true
        permalink: /:collection/:title
    coaching:
        output: true
        permalink: /oferta/:collection/:title
